config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#home'

  devise_for :users,
  			 path: '',
  			 path_name: {sign_in: 'login', sign_out: 'logout', edit: 'profile', sign_up: 'registration'},
  			 controllers: {omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations'}

 resources :users, only: [:show]
 resources :services, except: [:edit] do
  member do
    get 'listing'
    get 'pricing'
    get 'description'
    get 'photo_upload'
    get 'amenities'
    get 'location'
    get 'preload'
    get 'preview'
  end
  resources :photos, only: [:create, :destroy]
  resources :reservation_services, only: [:create]
 end

 resources :guest_review_services, only: [:create, :destroy]
 resources :host_review_services, only: [:create, :destroy]

 get '/preload' => 'reservation_services#preload' 
 get '/preview' => 'reservation_services#preview'


 get '/your_contracted_services' => 'reservation_services#your_contracted_services'
 get '/your_reservation_services' => 'reservation_services#your_reservation_services'
 #get '/reservation_service_info' => 'reservation_services#reservation_service_info'

 get 'search' => 'pages#search'

end

app/models/reservation_service.rb
class ReservationService < ActiveRecord::Base
  belongs_to :user
  belongs_to :service
end

app/controllers/reservation_services_controller.rb
class ReservationServicesController < ApplicationController
	before_action :authenticate_user!

  def preload
    service = Service.find(params[:service_id])
    today = Date.today
    reservation_services = service.reservation_services.where("start_date >= ? OR end_date >= ?", today, today)
    
    for i in 0..reservation_services.size-1 do 
      puts reservation_services[i].id
    end

    render json: reservation_services
    
  end

  def preview
    
    start_date = Date.parse(params[:start_date]) 
    end_date = Date.parse(params[:end_date])    

    render json: is_conflict(start_date, end_date).to_s

  end

  def create
  	service = Service.find(params[:service_id])

  	if current_user == service.user
      flash[:alert] = "Você não pode reservar seu próprio serviço!"
    else
      if !is_conflict(reservation_service_params[:start_date], reservation_service_params[:end_date]) 
  	  	start_date = Date.parse(reservation_service_params[:start_date])
  	  	end_date = Date.parse(reservation_service_params[:end_date])
  	  	days =(end_date - start_date).to_i + 1

  	  	@reservation_service = current_user.reservation_services.build(reservation_service_params)
  	  	@reservation_service.service = service
  	  	@reservation_service.price = service.price
  	  	@reservation_service.total = service.price * days
  	  	@reservation_service.save

  	  	flash[:notice] = "Reserva realizada com sucesso!"
      else
        flash[:alert] = "Há datas em conflito!"
      end        
	 end
	  redirect_to service
  end

  def your_reservation_services
    @services = current_user.services
    
  end

  def your_contracted_services
    @contracted_services = current_user.reservation_services.order(start_date: :asc)
  end

  #def reservation_service_info
  #  @service = Service.find(params[:service_id])
  #  @photos = service.photos
  #  @reservation_service = ReservationService.find_by(service_id: params[:service_id], user_id: current_user.id)
 # end

  private

    def is_conflict(start_date, end_date)
      service = Service.find(params[:service_id])
      puts start_date
      puts end_date
      check = service.reservation_services.where("? < start_date AND end_date < ?", start_date, end_date)
      
      puts check.size
      puts check.size > 0? true : false

      check.size > 0? true : false
    end

  	def reservation_service_params 
  		params.require(:reservation_service).permit(:start_date, :end_date)  		
  	end
end

app/views/reservation_services/_form.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <span><i class="fa fa-bolt" style="color: #ffb400"></i> R$<%= @service.price %></span>
    <span class="pull-right"><%= @service.payment_period %></span>
  </div>
  <div class="panel-body">
    <%= form_for([@service, @service.reservation_services.new]) do |f| %>
      <div class="row">
      	<% if @service.payment_period != "Por Hora" %>
	        <div class="col-md-6">
	          <label>Entrada</label>
	          <%= f.text_field :start_date, readonly: 'true', placeholder: "Data Inicial", class: "form-control datepicker" %>	         
	        </div>
	        <div class="col-md-6">
	          <label>Saída</label>	          
	          <%= f.text_field :end_date, readonly: 'true', placeholder: "Data Final", class: "form-control datepicker", disabled: 'true' %>
	        </div>
        <% else %>
	        <div class="col-md-6">
	          <label>Data</label>
	          <%= f.text_field :start_date, readonly: 'true', placeholder: "Data Inicial", class: "form-control datepicker" %>
	        </div>
	        <div class="col-md-6">
	          <label>Horário</label>
	          	<%= f.text_field :time_start, placeholder: "Hora Inicial", class: "form-control timepicker", id: "time_start" %>  
	          	<%= f.text_field :time_end, placeholder: "Hora Final", class: "form-control timepicker", id: "time_end"%>          
	        </div>
        <% end %>
      </div>

	<%= f.hidden_field :service_id, value: @service.id %>
	<%= f.hidden_field :price, value: @service.price %>


      <h4 class="message-alert text-center"><span id="message"></span></h4>      
      <div id="preview" style="display: none">
        <table class="reservation-table">
          <tbody>
            <tr>
              <td>Preço</td>
              <td class="text-right">R$ <%= @service.price %></td>
            </tr>
            <tr>
             <td><%= @service.payment_period %></td>
             <% if @service.payment_period == "Por Hora" %>          		
              	<td class="text-right">x <span id="reservation_service_hours"></span></td>
          	 <% else %>              	
              	<td class="text-right">x <span id="reservation_service_nights"></span></td>
             <% end %>
            </tr>
            <tr>
              <td class="total">Total</td>
              <td class="text-right">R$ <span id="reservation_service_total"></span></td>
            </tr>
          </tbody>
        </table>
      </div>

      <br/>

      <%= f.submit "Reservar Agora", id: "btn_book", class: "btn btn-normal btn-block" , disabled: 'true' %>
    <% end %>
  </div>
</div>


<script type="text/javascript"> 
	
	function checkDate(date) {
	    dmy = date.getDate() + "-" + (date.getMonth()+1) + "-" + date.getFullYear();
	    return [$.inArray(dmy, unavailableDates) == -1];
  	}

    $(function() {

    	unavailableDates = [];

    	$.ajax({
	      	url: '/preload',
	      	data: {'service_id': <%= @service.id %>},
	      	dataType: 'json',
	      	success: function(data) {

		        $.each(data, function(arrID, arrValue) {

		            for(var d = new Date(arrValue.start_date); d <= new Date(arrValue.end_date); d.setDate(d.getDate() +1)) {
					  	unavailableDates.push($.datepicker.formatDate('d-m-yy', d));					  	
	            	}
		        });
		    

		    	$('#reservation_service_start_date').datepicker({
		        	dateFormat: 'dd-mm-yy',
				    dayNames: ['Domingo','Segunda','Terça','Quarta','Quinta','Sexta','Sábado'],
				    dayNamesMin: ['D','S','T','Q','Q','S','S','D'],
				    dayNamesShort: ['Dom','Seg','Ter','Qua','Qui','Sex','Sáb','Dom'],
				    monthNames: ['Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro'],
				    monthNamesShort: ['Jan','Fev','Mar','Abr','Mai','Jun','Jul','Ago','Set','Out','Nov','Dez'],
				    nextText: 'Próximo',
				    prevText: 'Anterior',

				    minDate: 0,
		            maxDate: '3m',
		            beforeShowDay: checkDate,
		            onSelect: function(selected) {
			            $('#reservation_service_end_date').datepicker("option", "minDate", selected);
			            $('#reservation_service_end_date').attr('disabled', false);

			            var start_date = $('#reservation_service_start_date').datepicker('getDate');
			            var end_date = $('#reservation_service_end_date').datepicker('getDate');
			            var nights = (end_date - start_date)/1000/60/60/24+1;

			            var input = {
			                'start_date': start_date,
			                'end_date': end_date,
			                'service_id': <%= @service.id %>
			            }

			            $.ajax({
			                url: '/preview',
			                data: input,
			                dataType: 'json',			                
			                success: function(data) {			                	
			                	
				                if(data) {

				                  	$('#message').text("Estas datas não estão disponíveis.");
				                  	$('#preview').hide();
				                  	$('#btn_book').attr('disabled', true);

				                } else {
				                  	
				                  	$('#preview').show();
				                  	$('#btn_book').attr('disabled', false);

				                  	var total = nights * <%= @service.price %>
				                 	$('#reservation_service_nights').text(nights);
				                  	$('#reservation_service_total').text(total);
				                }
			                }
			            });
		          	} //onselect
				}); //datapicker

		        $('#reservation_service_end_date').datepicker({
		        	dateFormat: 'dd-mm-yy',
				    dayNames: ['Domingo','Segunda','Terça','Quarta','Quinta','Sexta','Sábado'],
				    dayNamesMin: ['D','S','T','Q','Q','S','S','D'],
				    dayNamesShort: ['Dom','Seg','Ter','Qua','Qui','Sex','Sáb','Dom'],
				    monthNames: ['Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro'],
				    monthNamesShort: ['Jan','Fev','Mar','Abr','Mai','Jun','Jul','Ago','Set','Out','Nov','Dez'],
				    nextText: 'Próximo',
				    prevText: 'Anterior',
		          	minDate: 0,
		          	maxDate: '3m',
		          	beforeShowDay: checkDate,
		          	onSelect: function(selected) {
			            $('#reservation_service_start_date').datepicker("option", "maxDate", selected);

			            var start_date = $('#reservation_service_start_date').datepicker('getDate');
			            var end_date = $('#reservation_service_end_date').datepicker('getDate');
			            var nights = (end_date - start_date)/1000/60/60/24 +1;

			            var input = {
			              	'start_date': start_date,
			              	'end_date': end_date,
			              	'service_id': <%= @service.id %>
			            }

			            $.ajax({
			              	url: '/preview',
			              	data: input,
			              	dataType: 'json',			              	
			              	success: function(data) {
			              		
				                if(data) {

				                  	$('#message').text("Estas datas não estão disponíveis.");
				                  	$('#preview').hide();
				                  	$('#btn_book').attr('disabled', true);

				                } else {
				                  	
				                  	$('#preview').show();
				                  	$('#btn_book').attr('disabled', false);

				                  	var total = nights * <%= @service.price %>
				                  	$('#reservation_service_nights').text(nights);
				                  	$('#reservation_service_total').text(total);
				                }
			                }
			            }); //ajax
		          	} //onselect

	        	}); //datapicker

	    }
		});
	});//function
        
    
 
</script>

<!-- Por Hora - timepicker AJEITAR O ONSELECT PARA CALCULAR TOTAL DE HORAS POR DIA-->
<script type="text/javascript">	
		
		$('#time_start').timepicker({ 
			step: 60,
			onSelect: function(selected) {
					    

				var start_date = $('#reservation_service_start_date').datepicker('getDate');			    
			    var nights = 1;
			    var time_start = $('#time_start').data('timepicker').getTime();
			    var time_end = $('#time_end').data('timepicker').getTime();		
			    var hours = time_end - time_start;
				$('#preview').show();
				$('#btn_book').attr('disabled', false);

				var total = nights * <%= @service.price %>
				$('#reservation_service_hours').text(hours);
				$('#reservation_service_total').text(total);
				               
				
		    } //onselect
		
		});
		$('#time_end').timepicker({ 
			step: 60,
			onSelect: function(selected) {				

				var start_date = $('#reservation_service_start_date').datepicker('getDate');			    
			    var nights = 1;
			    var time_start = $('#time_start').data('timepicker').getTime();
			    var time_end = $('#time_end').data('timepicker').getTime();		
			    var hours = time_end - time_start;   

			    $('#message').text(" Horas" + time_start + " a " + time_end);

			    var total = nights * <%= @service.price %> * hours;
				$('#reservation_service_hours').text(hours);				
				$('#reservation_service_total').text(total);
				
				
		    } //onselect
		});
	
</script>

app/views/reservation_services/your_contracted_services.html.erb
<div class="row">
  <div class="col-md-3">
    <ul class="sidebar-list">
      <li class="sidebar-item"><%= link_to "Serviços Anunciados", services_path, class: "sidebar-link" %></li>
      <li class="sidebar-item"><%= link_to "Serviços Reservados", your_reservation_services_path, class: "sidebar-link" %></li>
      <li class="sidebar-item"><%= link_to "Serviços Contratados", your_contracted_services_path, class: "sidebar-link active" %></li>
    </ul>
  </div>
  <div class="col-md-9">
  <% if @contracted_services.present? %>
    <div class="panel panel-default">      
      <div class="panel-heading">
        Serviços Contratados Abertos
      </div>
      <div class="panel-body">

        <% @contracted_services.each do |contracted_service| %>
          <% if contracted_service.end_date >= Time.now %>
            <div class="row">
              <div class="col-md-2">
                <span>
                  <%= contracted_service.start_date.strftime('%d/%m/%Y') %> a <br/>
                  <%= contracted_service.end_date.strftime('%d/%m/%Y') %>
                </span>
              </div>
              <div class="col-md-2">
                <%= link_to service_path(contracted_service.service) do %>
                  <%= image_tag contracted_service.service.cover_photo, :size => "80x50" %>
                <% end %>
              </div>
              <div class="col-md-5">
                <%= link_to contracted_service.service.listing_name, service_path(contracted_service.service) %><br/><br/>
                <span>
                  <%= image_tag avatar_url(contracted_service.service.user), class: "img-circle avatar-small" %>
                  <%= link_to user_path(contracted_service.service.user) do %>
                      <%= contracted_service.service.user.fullname %>
                  <% end %>
                </span>
              </div>
              
              <div class="col-md-3 text-right">
                <%= render partial: "review_services/guest_form", locals: {reservation_service: contracted_service} %>
              </div>

            </div>
            <hr/>
          <% end %>
        <% end %>
      </div>
    </div>
   
    <div class="panel panel-default">
      <div class="panel-heading">
        Serviços Contratados Encerrados
      </div>
      <div class="panel-body">

        <% @contracted_services.each do |contracted_service| %>
          <% if contracted_service.end_date < Time.now %>
            <div class="row">
              <div class="col-md-2">
                <span>
                  <%= contracted_service.start_date.strftime('%d/%m/%Y') %> a <br/>
                  <%= contracted_service.end_date.strftime('%d/%m/%Y') %>
                </span>
              </div>
              <div class="col-md-2">
                <%= link_to service_path(contracted_service.service) do %>
                  <%= image_tag contracted_service.service.cover_photo, :size => "80x50" %>
                <% end %>
              </div>
              <div class="col-md-5">
                <%= link_to contracted_service.service.listing_name, service_path(contracted_service.service) %><br/><br/>
                <span>
                  <%= image_tag avatar_url(contracted_service.service.user), class: "img-circle avatar-small" %>
                  <%= link_to user_path(contracted_service.service.user) do %>
                      <%= contracted_service.service.user.fullname %>
                  <% end %>
                </span>
              </div>
              
              <div class="col-md-3 text-right">
                <%= render partial: "review_services/guest_form", locals: {reservation_service: contracted_service} %>
              </div>

            </div>
            <hr/>
          <% end %>
        <% end %>
      </div>
    </div>
    <% else %>
      <div class="panel panel-default"> 
        <div class="panel-body">
          <span>Não há serviços contratados.</span>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/reservation_services/your_reservation_services.html.erb
<div class="row">
  <div class="col-md-3">
    <ul class="sidebar-list">
      <li class="sidebar-item"><%= link_to "Serviços Anunciados", services_path, class: "sidebar-link" %></li>
      <li class="sidebar-item"><%= link_to "Serviços Reservados", your_reservation_services_path, class: "sidebar-link active" %></li>
      <li class="sidebar-item"><%= link_to "Serviços Contratados", your_contracted_services_path, class: "sidebar-link" %></li>
    </ul>
  </div>
  <div class="col-md-9">
    <% has_reservation = false %>
    <% if @services.present? %>
      <% @services.each do |service| %>
        <% if service.reservation_services.present? %>
          <% has_reservation = true %>
          <div class="panel panel-default">
            <div class="panel-heading">
              Serviços Reservados Abertos
            </div>
            <div class="panel-body">                  
             <% service.reservation_services.each do |reservation| %>
              <% if reservation.end_date >= Time.now %>
                <div class="row">
                  <div class="col-md-2">
                   <span>
                      <%= reservation.start_date.strftime('%d/%m/%Y') %> a <br/>
                      <%= reservation.end_date.strftime('%d/%m/%Y') %>
                    </span>
                  </div>
                  <div class="col-md-2">
                    <%= link_to service_path(reservation.service) do %>
                        <%= image_tag reservation.service.cover_photo, :size => "80x50" %>
                    <% end %>
                  </div>
                  <div class="col-md-5">
                    <%= link_to reservation.service.listing_name, service_path(reservation.service) %><br/><br/>
                    <span>
                      <%= link_to user_path(reservation.user) do %>
                        <%= image_tag avatar_url(reservation.user), class: "img-circle avatar-small" %>
                        <%= reservation.user.fullname %>
                      <% end %>
                    </span>
                  </div>
                 
                  <div class="col-md-3 text-right">
                    <%= render partial: "review_services/host_form", locals: {reservation_service: reservation} %>
                  </div>
                  
                </div>
                <hr/>
              <% end %> <!-- IF -->
             <% end %> <!-- EACH -->
            </div>
          </div>
        <% end %> <!-- IF -->
      <% end %> <!-- EACH -->
    <% end %> <!-- IF -->
  
    <% if @services.present? %>
      <% @services.each do |service| %>
        <% if service.reservation_services.present? %>
          <% has_reservation = true %>
          <div class="panel panel-default">
            <div class="panel-heading">
              Serviços Reservados Encerrados
            </div>
            <div class="panel-body">
              <% service.reservation_services.each do |reservation| %>
                <% if reservation.end_date < Time.now %>
                  <div class="row">
                    <div class="col-md-2">
                      <span>
                        <%= reservation.start_date.strftime('%d/%m/%Y') %> a <br/>
                        <%= reservation.end_date.strftime('%d/%m/%Y') %>
                      </span>
                    </div>
                    <div class="col-md-2">
                      <%= link_to service_path(reservation.service) do %>
                          <%= image_tag reservation.service.cover_photo, :size => "80x50" %>
                      <% end %>
                    </div>
                    <div class="col-md-5">
                      <%= link_to reservation.service.listing_name, service_path(reservation.service) %><br/><br/>
                      <span>
                        <%= link_to user_path(reservation.user) do %>
                          <%= image_tag avatar_url(reservation.user), class: "img-circle avatar-small" %>
                          <%= reservation.user.fullname %>
                        <% end %>
                      </span>
                    </div>                    
                    <div class="col-md-3 text-right">
                      <%= render partial: "review_services/host_form", locals: {reservation_service: reservation} %>
                    </div>
                  </div>
                  <hr/>
                <% end %> <!-- IF -->
              <% end %> <!-- EACH -->
            </div>
          </div>
        <% end %> <!-- IF -->
      <% end %> <!-- EACH -->
    <% end %> <!-- IF -->

    <% if has_reservation == false %>      
      <div class="panel panel-default"> 
        <div class="panel-body">
          <span>Não há serviços reservados.</span>
        </div>
      </div>
    <% end %>
  </div>  
</div>