config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#home'

  devise_for :users,
  			 path: '',
  			 path_name: {sign_in: 'login', sign_out: 'logout', edit: 'profile', sign_up: 'registration'},
  			 controllers: {omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations'}

 resources :users, only: [:show]
 resources :services, except: [:edit] do
  member do
    get 'listing'
    get 'pricing'
    get 'description'
    get 'photo_upload'
    get 'amenities'
    get 'location'
    get 'preload'
    get 'preview'
  end
  resources :photos, only: [:create, :destroy]
  resources :reservation_services, only: [:create]
 end

 resources :guest_review_services, only: [:create, :destroy]
 resources :host_review_services, only: [:create, :destroy]

 get '/preload' => 'reservation_services#preload' 
 get '/preview' => 'reservation_services#preview'


 get '/your_contracted_services' => 'reservation_services#your_contracted_services'
 get '/your_reservation_services' => 'reservation_services#your_reservation_services'
 #get '/reservation_service_info' => 'reservation_services#reservation_service_info'

 get 'search' => 'pages#search'

end

app/models/service.rb
class Service < ActiveRecord::Base
  belongs_to :user
  has_many :photos
  has_many :reservation_services
  has_many :guest_review_services
  
  #geocoded_by :address
  #after_validation :geocode, if: :address_changed?

  validates :service_category, presence: true
  validates :service_type, presence: true
  validates :service_mode, presence: true
  validates :payment_period, presence: true

  def cover_photo
    if self.photos.length > 0
      self.photos[0].image.url()
    else
      "11.png"
    end
  end

  def average_rating
    guest_review_services.count == 0 ? 0 : guest_review_services.average(:star).round(2).to_i
    
  end
 
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  
  before_action :set_service, except: [:index, :new, :create]
  before_action :authenticate_user!, except: [:show]
  before_action :is_authorized, only: [:listing, :pricing, :description, :photo_upload, :amenities, :location, :update]

  def index
    @services = current_user.services
  end

  def new
    @service = current_user.services.build
  end

  def create
    @service = current_user.services.build(service_params)
    if @service.save
      redirect_to listing_service_path(@service), notice: "Serviço salvo sucesso."
    else
      flash[:alert] = "O cadastro do serviço não foi realizado."
    end

  end

  def listing
    
  end

  def pricing

  end

  def description
   
  end

  def photo_upload
    @photos = @service.photos
  end

  def amenities
  end

  def location
  end

  def show     
    @photos = @service.photos
    @guest_review_services = @service.guest_review_services
  end

  def update
    new_params = service_params
    new_params = service_params.merge(active: true) if is_ready_service

    if @service.update(new_params)
      flash[:notice] = "Serviço alterado com sucesso."
    else
      flash[:alert] =  "A alteração do serviço não foi realizada."
    end
    redirect_to :back
  end

  

  private

    

    def set_service
      @service = Service.find(params[:id])
    end

    def is_authorized
      redirect_to root_path flash[:alert] =  "Você não tem permissão para realizar esta operação." unless current_user.id == @service.user_id
      
    end

    def is_ready_service
      !@service.active && !@service.price.blank? && !@service.listing_name.blank? && !@service.address.blank?
    end

    def service_params
      params.require(:service).permit(:service_category, :service_type, :service_mode, 
        :payment_period, :listing_name, :summary, :address, :photo_upload,
        :is_independent, :is_legal_person, :has_invoice,
         :has_garantee, :price, :active)      
    end

    
end

app/helpers/service_helper.rb
module ServiceHelper
end

app/views/services/_service_menu.html.erb
<div>
  <h3>Serviço</h3>
</div>
<ul class="sidebar-list">
  <li class="sidebar-item">
    <%= link_to "Informações", listing_service_path, class: "sidebar-link active" %>
    <span class="pull-right text-babu"><i class="fa fa-check"></i></span>
  </li>
  <li class="sidebar-item">
    <%= link_to "Preço", pricing_service_path, class: "sidebar-link active" %>
    <% if !@service.price.blank? %>
      <span class="pull-right text-babu"><i class="fa fa-check"></i></span>
    <% end %>
  </li>
  <li class="sidebar-item">
    <%= link_to "Descrição", description_service_path, class: "sidebar-link active" %>
    <% if !@service.listing_name.blank? %>
      <span class="pull-right text-babu"><i class="fa fa-check"></i></span>
    <% end %>
  </li>
  <li class="sidebar-item">
    <%= link_to "Fotos", photo_upload_service_path, class: "sidebar-link active" %>
    <% if !@service.photos.blank? %>
      <span id="photo_check" class="pull-right text-babu"><i class="fa fa-check"></i></span>
    <% end %>
  </li>  
  <li class="sidebar-item">
    <%= link_to "Localização", location_service_path, class: "sidebar-link active" %>
    <% if !@service.address.blank? %>
      <span class="pull-right text-babu"><i class="fa fa-check"></i></span>
    <% end %>
  </li>
  <li class="sidebar-item">
    <%= link_to "Detalhes", amenities_service_path, class: "sidebar-link active" %>
    <% if !@service.is_independent.nil? %>
      <span class="pull-right text-babu"><i class="fa fa-check"></i></span>
    <% end %>
  </li>
</ul>
<hr/>

<% is_ready = !@service.active && !@service.price.blank? && !@service.listing_name.blank? && !@service.address.blank? && !@service.is_independent.nil? %>

<%= form_for @service do |f| %>
  <%= f.hidden_field :active, value: true %>
  <%= f.submit "Publicar Serviço", id: "publish_button", class: "btn btn-normal btn-block", disabled: !is_ready %>
<% end %>
<% if @service.active? %>
  <%= form_for @service do |f| %>
    <%= f.hidden_field :active, value: false %>
    <%= f.submit "Despublicar Serviço", id: "unpublish_button", class: "btn btn-default btn-block", disabled: !@service.active %>
  <% end %>
<% end %> 

app/views/services/_services_list.html.erb
<% services.each do |service| %>
  <% if service.active %>
    <div class="col-md-4">
      <div class="panel panel-default">
        <div class="panel-heading preview">
          <%= image_tag service.cover_photo, :size => "150x300" %>
        </div>
        <div class="panel-body">
          <%= link_to service.listing_name, service %><br/>
          $<%= service.price %> - <%= service.service_type %> 
          <div id="star_<%= service.id %>"></div> <%= pluralize(service.average_rating, "Comentário") %>
        </div>
      </div>
    </div>
    <% end %>
    
    <script>
      $('#star_<%= service.id %>').raty({
        path: '/assets',
        readOnly: true,
        score: <%= service.average_rating %>
      });
    </script>
<% end %>

app/views/services/amenities.html.erb
<div class="row">
  <div class="col-md-3">
    <%= render 'service_menu' %>
  </div>
  <div class="col-md-9">
    <div class="panel panel-default">

      <div class="panel-heading">
        Detalhes
      </div>

      <div class="panel-body">
        <div class="container">
         
        	<%= form_for @service do |f| %>
              	<div class="row form-group">
	              	<div class="col-md-6">
	              		<%= f.check_box :is_independent %> Autônomo
	              	</div>
                  <div class="col-md-6">
                    <%= f.check_box :is_legal_person %> Tem CNPJ
                  </div>
                </div>
                <div class="row form-group">
                  <div class="col-md-6">
                    <%= f.check_box :has_invoice %> Emite nota fiscal
                  </div>
                  <div class="col-md-6">
                    <%= f.check_box :has_garantee %> Dá garantia
                  </div>
	              </div>
  	            
                <br/><br/>

                <div class="text-center">                  
                  <%= f.submit "Salvar", class: "btn btn-form" %>
                </div>
            <% end %>        
        </div>
      </div>

    </div>
  </div>
</div>

app/views/services/create.html.erb
<h1>Service#create</h1>
<p>Find me in app/views/service/create.html.erb</p>

app/views/services/description.html.erb
<div class="row">
  <div class="col-md-3">
    <%= render 'service_menu' %>
  </div>
  <div class="col-md-9">
    <div class="panel panel-default">

      <div class="panel-heading">
        Descrição
      </div>

      <div class="panel-body">
        <div class="container">
        	<%= form_for @service do |f| %>
              	<div class="row">
	              	<div class="form-group">
	              		<label>Título</label>
	              		<%= f.text_field :listing_name, placeholder: "Qual o nome do seu serviço?", class: "form-control", required: true %>
	              	</div>
	            </div>
	            <div class="row">
	              	<div class="form-group">
	              		<label>Descrição</label>
	              		<%= f.text_area :summary, rows: 5, cols: 25, placeholder: "Descreva o seu serviço detalhadamente.", class: "form-control", required: true%>
	              	</div>
	            </div>
	            <div class="text-center">
	            	<%= f.submit "Salvar", class: "btn btn-form" %>
	            </div>
            <% end %>        
        </div>
      </div>

    </div>
  </div>
</div>

app/views/services/index.html.erb
<div class="row">
  <div class="col-md-3">
    <ul class="sidebar-list">
      <li class="sidebar-item"><%= link_to "Serviços Anunciados", services_path, class: "sidebar-link active" %></li>
      <li class="sidebar-item"><%= link_to "Serviços Reservados", your_reservation_services_path, class: "sidebar-link" %></li>
      <li class="sidebar-item"><%= link_to "Serviços Contratados", your_contracted_services_path, class: "sidebar-link" %></li>      
    </ul>
  </div>
  <div class="col-md-9">
    <div class="panel panel-default">
      <div class="panel-heading">
        Serviços Anunciados
      </div>
      <div class="panel-body">

        <% @services.each do |service| %>
          <div class="row">
            <div class="col-md-2">
              
              <%= image_tag service.cover_photo, :size => "80x50"%>              
            </div>
            <div class="col-md-7">
              <h4><%= link_to service.listing_name, service %></h4>
            </div>
            <div class="col-md-2 right">
              <%= link_to "Editar", listing_service_path(service), class: "btn btn-form" %>
            </div>
            <div class="col-md-1 right">
              <% if service.active %>
                <i class="fa fa-check fa-lg" title="Publicado"></i>
              <% else %>
                <i class="fa fa-ban fa-lg" title="Despublicado"></i>
              <% end %>
            </div>
          </div>
          <hr/>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/services/listing.html.erb
<div class="row">
  <div class="col-md-3">
    <%= render 'service_menu' %>
  </div>
  <div class="col-md-9">
    <div class="panel panel-default">

      <div class="panel-heading">
        Informações
      </div>

      <div class="panel-body">
        <div class="container">
        	<%= form_for @service do |f| %>

		        <div class="row">

		          <div class="col-md-6 select">
		            <div class="form-group">
		              <label>Categoria do Serviço</label>
		              <div>
		              	<%= f.select :service_category, [["Casa ", "Casa "], ["Ensino", "Ensino"], ["Saúde", "Saúde"], ["Pessoal", "Pessoal"], ["Viagem", "Viagem"]],
		                	id: "service_category", prompt: "Selecione", class: "form-control" %>
		                </div>
		            </div>
		          </div>

		          <div class="col-md-6 select">
		            <div class="form-group">
		              <label>Serviço</label>
		              <div>
		              	<%= f.select :service_type, [["Cabeleireira", "Cabeleireira"], ["Faxineira", "Faxineira"], ["Enfermeira", "Enfermeira"], ["Professor", "Professor"], ["Guia Turístico", "Guia Turístico"]],
		                	id: "service_type", prompt: "Selecione", class: "form-control" %>
		               </div>
		            </div>
		          </div>

		          <div class="col-md-6 select">
		            <div class="form-group">
		              <label>Modo de Atendimento</label>
		              <div>
		              	<%= f.select :service_mode, [["Em Domicílio", "Em Domicílio"], ["No Estabelecimento", "No Estabelecimento"]],
		                	id: "service_mode", prompt: "Selecione", class: "form-control" %>
		              </div>
		            </div>
		          </div>

		          <div class="col-md-6 select">
		            <div class="form-group">
		              <label>Periodicidade do Pagamento</label>
		              <div>
		              	<%= f.select :payment_period, [["Gratuito", "Gratuito"], ["A definir", "A definir"], ["Por Serviço", "Por Serviço"], ["Por Hora", "Por Hora"], ["Por Dia", "Por Dia"], ["Por Semana", "Por Semana"], ["Por Mês", "Por Mês"]],
		                	id: "payment_period", prompt: "Selecione", class: "form-control" %>
		              </div>
		            </div>
		          </div>

		        </div>

		        <div class="text-center">
          			<%= f.submit "Salvar", class: "btn btn-form" %>
        		</div>

		      <% end %>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/services/location.html.erb
<div class="row">
  <div class="col-md-3">
    <%= render 'service_menu' %>
  </div>
  <div class="col-md-9">
    <div class="panel panel-default">

      <div class="panel-heading">
        Localização
      </div>

      <div class="panel-body">
        <div class="container">
        	<%= form_for @service do |f| %>
              	<div class="row">
	              	<div class="form-group">
	              		<label>Endereço</label>
	              		<%= f.text_field :address, placeholder: "Qual o endereço do seu serviço?", class: "form-control", required: true%>
	              	</div>
	            </div>
	            <div class="text-center">
	            	<%= f.submit "Salvar", class: "btn btn-form" %>
	            </div>
            <% end %>        
        </div>
      </div>

    </div>
  </div>
</div>

<script>
  $(function() {
    $("#autoaddress").geocomplete();
  })
</script>

app/views/services/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    Publique seu Serviço
  </div>
  <div class="panel-body">
    <div class="container">

      <%= form_for @service do |f| %>

        <div class="row">

          <div class="col-md-6 select">
            <div class="form-group">
              <label>Categoria do Serviço</label>
              <%= f.select :service_category, [["Casa ", "Casa "], ["Ensino", "Ensino"], ["Saúde", "Saúde"], ["Pessoal", "Pessoal"], ["Viagem", "Viagem"]], 
                id: "service_category", prompt: "Selecione", class: "form-control" %>
            </div>
          </div>

          <div class="col-md-6 select">
            <div class="form-group">
              <label>Serviço</label>
              <%= f.select :service_type, [["Cabeleireira", "Cabeleireira"], ["Faxineira", "Faxineira"], ["Enfermeira", "Enfermeira"], ["Professor", "Professor"], ["Guia Turístico", "Guia Turístico"]], 
                id: "service_type", prompt: "Selecione", class: "form-control" %>
            </div>
          </div>

          <div class="col-md-6 select">
            <div class="form-group">
              <label>Modo de Atendimento</label>
              <%= f.select :service_mode, [["Em Domicílio", "Em Domicílio"], ["No Estabelecimento", "No Estabelecimento"]], 
                id: "service_mode", prompt: "Selecione", class: "form-control" %>
            </div>
          </div>

          <div class="col-md-6 select">
            <div class="form-group">
              <label>Periodicidade do Pagamento</label>
              <%= f.select :payment_period, [["Gratuito", "Gratuito"], ["Por Hora", "Por Hora"], ["Por Dia", "Por Dia"], ["Por Semana", "Por Semana"], ["Por Mês", "Por Mês"]], 
                id: "payment_period", prompt: "Selecione", class: "form-control" %>
            </div>
          </div>          

        </div>

        <div class="text-center">
          <%= f.submit "Criar meu Serviço", class: "btn btn-form" %>          
        </div>

      <% end %>

    </div>
  </div>
</div>

app/views/services/photo_upload.html.erb
<div class="row">
  <div class="col-md-3">
    <%= render 'service_menu' %>
  </div>
  <div class="col-md-9">
    <div class="panel panel-default">

      <div class="panel-heading">
        Fotos
      </div>

      <div class="panel-body">
        <div class="container">
          <div class="row">
            <div class="col-md-offset-3 col-md-12">
              <span id="photo_required" style="color:red; display:none;">Adicione pelo menos 1 foto.</span>
            </div>
          </div>
          <div class="row">
            <div class="col-md-offset-3 col-md-6">              
              <!-- PHOTOS UPLOAD GOES HERE -->
              <%= form_for @service, url: service_photos_path(@service), method: 'post', html: {multipart: true} do |f| %>
                <div class="row">
                  <div class="form-group">
                    <span class="btn btn-default btn-file text-babu">
                      <i class="fa fa-cloud-upload" aria-hidden="true"></i> Selecione as Fotos
                      <%= file_field_tag "images[]", type: :file, multiple: true %>
                    </span>  
                  </div>
                </div>

                <div class="text-center">
                  <%= f.submit "Adicionar Fotos", class: "btn btn-form" %>

                </div>

              <% end %>
            </div>
          </div>
         
         <div id="photos"><%= render 'photos/photos_list' %></div>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/services/pricing.html.erb
<div class="row">
  <div class="col-md-3">
    <%= render 'service_menu' %>
  </div>
  <div class="col-md-9">
    <div class="panel panel-default">

      <div class="panel-heading">
        Preço
      </div>

      <div class="panel-body">
        <div class="container">
        	<%= form_for @service do |f| %>
              	<div class="row">
	              	<div class="form-group">
	              		<label>Preço (R$)</label>
	              		<%= f.text_field :price, placeholder: "p.e: R$ 100,00", class: "form-control" %>
	              	</div>
	            </div>
	            <div class="text-center">
	            	<%= f.submit "Salvar", class: "btn btn-form" %>
	            </div>
            <% end %>        
        </div>
      </div>

    </div>
  </div>
</div>

app/views/services/show.html.erb
<!-- Image -->
<div class="row">
  <div class="col-md-12">
    <%= image_tag @service.cover_photo, height: "300px" %>
  </div>
</div>
<br/>

<div class="row">

  <!-- LEFT PANEL -->
  <div class="col-md-8">

    <!-- Listing Name -->
    <div class="row">
      <div class="col-md-8">
        <h1><%= @service.listing_name %></h1>
        <%= @service.address %>
      </div>
      <div class="col-md-4 text-center">
        <%= image_tag avatar_url(@service.user), class: "img-circle avatar-large" %><br/><br/>
        <%= link_to user_path(@service.user) do %>
          <%= @service.user.fullname %>
        <% end %>        
      </div>
    </div>
    <hr/>

    <!-- Room Info -->
    <div class="row text-babu">
      <div class="row text-center row-space-1">
        <div class="col-md-3">
          <i class="fa fa-university fa-2x"></i>
        </div>
        <div class="col-md-3">
          <i class="fa fa-user-circle-o fa-2x"></i>
        </div>
        <div class="col-md-3">
          <i class="fa fa-hourglass-half fa-2x"></i>
        </div>
        <div class="col-md-3">
          <i class="fa fa-home fa-2x"></i>
        </div>      
      </div>

      <div class="row text-center">
        <div class="col-md-3"><%= @service.service_category %></div>
        <div class="col-md-3"><%= @service.service_type  %></div>
        <div class="col-md-3"><%= @service.payment_period %></div>
        <div class="col-md-3"><%= @service.service_mode %></div>    
      </div>

    </div>
    <hr/>

    <!-- About -->
    <div class="row">
      <div class="col-md-12">
        <h3>Informações</h3>
        <p><%= @service.summary %></p>
      </div>
    </div>
    <hr/>

    <!-- Amenities -->
    <div class="row">
      <div class="col-md-3">
        <h4>Detalhes</h4>
      </div>

      <div class="col-md-9">
        <div class="row">
          <div class="col-md-6">
            <ul class="amenities">
              <li class="<%= 'text-line-through' if !@service.is_independent %>">Autônomo</li>
              <li class="<%= 'text-line-through' if !@service.is_legal_person %>">Tem CNPJ</li>             
            </ul>
          </div>
          <div class="col-md-6">
            <ul class="amenities">
              <li class="<%= 'text-line-through' if !@service.has_invoice %>">Emite nota fiscal</li>
              <li class="<%= 'text-line-through' if !@service.has_garantee %>">Dá garantia</li>
            </ul>
          </div>

        </div>
      </div>

    </div>
    <hr/>

    <!-- Carousel -->
    <div class="row">

      <% if @photos.length > 0 %>
          <div id="myCarousel" class="carousel slide" data-ride="carousel">
          <!-- Indicators -->
          <ol class="carousel-indicators">
            <% @photos.each do |photo| %>
                <li data-target="#myCarousel" data-slide-to="<%= photo.id %>"></li>
            <% end %>
          </ol>

          <!-- Wrapper for slides -->
          <div class="carousel-inner">
            <% @photos.each do |photo| %>
                <div class="item <%= 'active' if photo.id == @photos[0].id %>">
                  <%= image_tag photo.image.url() %>
                </div>
            <% end %>
          </div>

          <!-- Left and right controls -->
          <a class="left carousel-control" href="#myCarousel" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left"></span>
            <span class="sr-only">Anterior</span>
          </a>
          <a class="right carousel-control" href="#myCarousel" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right"></span>
            <span class="sr-only">Próxima</span>
          </a>
        </div>
      <% end %>

    </div>
    <hr/>

    <!-- REVIEWS -->
    <div class="row">
      <div class="col-md-12">
        <h3>
          <%= pluralize(@guest_review_services.count, "Comentário") %>
          <span id="average_rating"></span>
        </h3>
        <div class="container">
          <div><%= render "review_services/guest_list" %></div>
        </div>
      </div>
    </div>
    <br/>
    <hr/>

    

  </div>


  <!-- RIGHT PANEL -->
  <div class="col-md-4">
    <!-- Reservation Form -->
    <%= render 'reservation_services/form' %>
  </div>
</div>

<script>
  $('#average_rating').raty({
    path: '/assets',
    readOnly: true,
    score: <%= @service.average_rating %>
  });
</script>

app/views/services/update.html.erb
<h1>Service#update</h1>
<p>Find me in app/views/service/update.html.erb</p>