config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#home'

  devise_for :users,
  			 path: '',
  			 path_name: {sign_in: 'login', sign_out: 'logout', edit: 'profile', sign_up: 'registration'},
  			 controllers: {omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations'}

 resources :users, only: [:show]
 resources :services, except: [:edit] do
  member do
    get 'listing'
    get 'pricing'
    get 'description'
    get 'photo_upload'
    get 'amenities'
    get 'location'
    get 'preload'
    get 'preview'
  end
  resources :photos, only: [:create, :destroy]
  resources :reservation_services, only: [:create]
 end

 resources :guest_review_services, only: [:create, :destroy]
 resources :host_review_services, only: [:create, :destroy]

 get '/preload' => 'reservation_services#preload' 
 get '/preview' => 'reservation_services#preview'


 get '/your_contracted_services' => 'reservation_services#your_contracted_services'
 get '/your_reservation_services' => 'reservation_services#your_reservation_services'
 #get '/reservation_service_info' => 'reservation_services#reservation_service_info'

 get 'search' => 'pages#search'

end

app/views/shared/_devisemes.html.erb
<% unless resource.errors.empty? %>
  <script type="text/javascript">
    <% resource.errors.full_messages.each do |value| %>
      toastr.error('<%= value %>')
    <% end %>
  </script>
<% end %>

app/views/shared/_message.html.erb
<% unless flash.empty? %>
  <script type="text/javascript">
    <% flash.each do |key, value| %>
      <% type = key.to_s.gsub('alert', 'error').gsub('notice', 'info') %>
      toastr['<%= type %>']('<%= value %>')
    <% end %>
  </script>
<% end %>

app/views/shared/_navbar.html.erb
<!-- Static navbar -->
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-header">  
      <div class="panel-heading">  
        <%= link_to image_tag("logo_04_mn.png", :size => "150x40"), root_path %>
      </div>
    </div>
    <div id="navbar" class="navbar-collapse collapse">      

      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to new_service_path do %>
            <i class="fa fa-home fa-lg"></i> Crie seu Anúncio
          <% end %>
        </li>
        <li>
          <a href="#">
            <i class="fa fa-envelope-o"></i> Mensagens
          </a>
        </li>
        <% if (!user_signed_in?) %>         
          <li><%= link_to "Cadastre-se", new_user_registration_path %> </li>
          <li><%= link_to "Entrar", new_user_session_path %> </li>
        <% else %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
              <% if !(avatar_url(current_user) == Digest::MD5::hexdigest(current_user.email).downcase) %>
                <%= image_tag avatar_url(current_user), class: "img-circle avatar-small"  %>&nbsp;
              <% end %>
             
            <ul class="dropdown-menu">
              <li><%= link_to "Editar Perfil", edit_user_registration_path %></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Gerenciar Lugares</a></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Anuncie seu Serviço", new_service_path %></li>
              <li><%= link_to "Serviços Anunciados", services_path %></li>
              <li><%= link_to "Serviços Reservados", your_reservation_services_path %></li>
              <li><%= link_to "Serviços Contratados", your_contracted_services_path %></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Gerenciar Eventos</a></li>
              <li role="separator" class="divider"></li>              
              <li><a href="#">Configurações da Conta</a></li>
              <li><%= link_to "Sair", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>