config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#home'

  devise_for :users,
  			 path: '',
  			 path_name: {sign_in: 'login', sign_out: 'logout', edit: 'profile', sign_up: 'registration'},
  			 controllers: {omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations'}

 resources :users, only: [:show]
 resources :services, except: [:edit] do
  member do
    get 'listing'
    get 'pricing'
    get 'description'
    get 'photo_upload'
    get 'amenities'
    get 'location'
    get 'preload'
    get 'preview'
  end
  resources :photos, only: [:create, :destroy]
  resources :reservation_services, only: [:create]
 end

 resources :guest_review_services, only: [:create, :destroy]
 resources :host_review_services, only: [:create, :destroy]

 get '/preload' => 'reservation_services#preload' 
 get '/preview' => 'reservation_services#preview'


 get '/your_contracted_services' => 'reservation_services#your_contracted_services'
 get '/your_reservation_services' => 'reservation_services#your_reservation_services'
 #get '/reservation_service_info' => 'reservation_services#reservation_service_info'

 get 'search' => 'pages#search'

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :service

  has_attached_file :image #, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def create
  	@service = Service.find(params[:service_id])

  	if params[:images]
  		 params[:images].each do |img|
  		 	@service.photos.create(image: img)
  		 end
  		 @photos = @service.photos  		 
  		 flash[:notice] = "Imagem enviada com sucesso."
    end
    redirect_to :back
  end

  def destroy
    @photo = Photo.find(params[:id])
    @service = @photo.service

    @photo.destroy
    @photos = Photo.where(service_id: @service.id)

    respond_to :js
  end
end

app/views/photos/_photos_list.html.erb
<% if @photos.count > 0 %>
  <br/><br/>

  <div class="row">
    <% @photos.each do |photo| %>
      <div class="col-md-4">
        <div class="panel panel-default">
          <div class="panel-heading preview">
            <%= image_tag photo.image.url() %>
          </div>
          <div class="panel-body">
            <span class="pull-right">
              <%= link_to service_photo_path(photo.service_id, photo), remote: true, method: :delete, data: {confirm: "Are you sure?"} do %>
                <i class="fa fa-trash-o" aria-hidden="true"></i> 
              <% end %>
            </span>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/photos/destroy.js.erb
$('#photos').html("<%= j render 'photos_list' %>")
<% if @service.photos.blank? %>
  $('#photo_check').hide();  
  $('#unpublish_button').click();
  $('#unpublish_button').attr('disabled', false);
  $('#photo_required').show();
<% end %>

<% if !@service.active && !@service.price.blank? && !@service.listing_name.blank? && !@service.address.blank?  && !@service.is_independent.nil? %>
    $('#publish_button').attr('disabled', false);
    $('#unpublish_button').attr('disabled', true);    
<% else %>
    $('#publish_button').attr('disabled', true);
    $('#unpublish_button').attr('disabled', false);
    $('#photo_required').show();
<% end %>